# used limited resources to allow this
# deployment to be tested on local systems.
# Recommended values can be found in README and 
# in the values file in this chart.

small_resource_limit: &small_resource_limit
  limits:
    memory: "500Mi"
    cpu: "250m"

gtm:
  resources: *small_resource_limit
  pvc:
    resources:
      requests:
        storage: 100Mi

coordinators:
  count: 2
  resources: *small_resource_limit
  pvc:
    resources:
        requests:
          storage: 100Mi
proxies:
  resources: *small_resource_limit
  count: 1
  enabled: true

# this is the costly bit.
datanodes:
  count: 2
  resources: *small_resource_limit
  pvc:
    resources:
      requests:
        storage: "4Gi"
