{{ $app_name := include "global.app_name" . -}}
{{ $chart_name := include "global.chart_full_name" . -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{$app_name}}-scripts
  labels:
    app: {{ $app_name }}
    chart: {{ $chart_name }}
data:

  ######################
  # Load scripts from the scripts directory.
{{ $root := . }}
{{ range $path, $bytes := .Files.Glob "scripts/**" }}
{{ base $path | indent 2}}: |-
{{ $root.Files.Get $path | indent 4}}
{{ end }}  
