{{ $app_name := include "global.app_name" . -}}
{{ $chart_name := include "global.chart_full_name" . -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{$app_name}}-cfg
  labels:
    app: {{ $app_name }}
    chart: {{ $chart_name }}
data:
  config_append: |
    # applies only on startup.
    listen_addresses = '*'
{{- if .Values.config.append }}
{{ .Values.config.append | indent 4 }}
{{- end }}

  pg_config_append: |
    # applies only on startup.
    log_min_messages = {{ lower .Values.config.log_level }}

  gtm_config_append: |
    # applies only on startup.
    log_min_messages = {{ upper .Values.config.log_level }}

  host_aliases: | 
    # list of hosts to alias, for datanode and coordinators.
    # These short names are required by pg since the host 
    # name is truncated by the Create Node sql query.
    local-alias-gtm {{ $app_name }}-gtm-0.{{ $app_name }}-svc-gtm

{{- range $i := until (int .Values.datanodes.count) }}
    local-alias-dn-{{ $i }} {{ $app_name }}-dn-{{ $i }}.{{ $app_name }}-svc-dn
{{- end }}

{{- range $i := until (int .Values.coordinators.count) }}
    local-alias-crd-{{ $i }} {{ $app_name }}-crd-{{ $i }}.{{ $app_name }}-svc-crd
{{- end }}

{{- range $i := until (int .Values.proxies.count) }}
    local-alias-pxy-{{ $i }} {{ $app_name }}-pxy-{{ $i }}.{{ $app_name }}-svc-pxy
{{- end }}

