{{ $app_name := include "global.app_name" . -}}
{{ $chart_name := include "global.chart_full_name" . -}}
{{- $config_col := .Values.datanodes -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $app_name }}-svc-dn
  labels:
    app: {{ $app_name }}
    chart: {{ $chart_name }}
    type: datanode
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.config.postgres_port }}
    name: pg
  selector:
    app: {{ $app_name }}
    chart: {{ $chart_name }}
    type: datanode
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: {{ $app_name }}-dn
  labels:
    app: {{ $app_name }}
    chart: {{ $chart_name }}
    type: datanode
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
spec:
  serviceName: {{ $app_name }}-svc-dn 
  replicas: {{ .Values.datanodes.count }}
  podManagementPolicy: Parallel
  volumeClaimTemplates:
{{- if $config_col.pvc }}
    - metadata:
        name: datastore
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
{{ toYaml $config_col.pvc | indent 8 }}
{{- end }}
{{- if .Values.WAL.archive.enable }}
{{- if .Values.WAL.archive.pvc }}
    - metadata:
        name: wal-archive
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
{{ toYaml .Values.WAL.archive.pvc | indent 8 }}
{{- end }}
{{- end }}
{{- if $config_col.addVolumeClaims }}
{{ toYaml $config_col.addVolumeClaims | indent 4 }}
{{- end }}
  selector:
    matchLabels:
      app: {{ $app_name }}
      chart: {{ $chart_name }}
      type: datanode
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 6 }}
{{- end }}
  template:
    metadata:
      labels:
        app: {{ $app_name }}
        chart: {{ $chart_name }}
        type: datanode
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 8 }}
{{- end }}
    spec:
      securityContext:
        fsGroup: 3000
{{- if $config_col.injectSpecYaml }}
{{ toYaml $config_col.injectSpecYaml | indent 6 }}
{{- end }}
      containers:
      - name: datanode
        image: {{ .Values.image }}
        ports:
          - containerPort: {{ .Values.config.postgres_port }}
            name: pg
        command:
          - bash
          - /scripts/data_node_entrypoint
        readinessProbe:
          exec:
            command:
            - /scripts/probe_readiness_datanode
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - /scripts/probe_liveness_postgres
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
{{- if $config_col.resources }}
{{ toYaml $config_col.resources | indent 10 }}
{{- end }}
        envFrom:
        - configMapRef:
            name: {{$app_name}}-envs
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NODE_TYPE
            value: datanode
{{- include "print_password_envs" . | indent 10 }}
        volumeMounts:
          - name: {{$app_name}}-scripts
            mountPath: /scripts
          - name: {{$app_name}}-cfg
            mountPath: /config
          - name: datastore
            mountPath: {{ .Values.homedir }}/storage
{{- if .Values.WAL.archive.enable }}
          - name: wal-archive
            mountPath: "{{ .Values.homedir }}/wal_archive"
{{- end }}
{{- if $config_col.volumeMounts }}
{{ toYaml $config_col.volumeMounts | indent 10 }}
{{- end }}
{{- if $config_col.injectMainContainerYaml }}
{{ toYaml $config_col.injectMainContainerYaml | indent 8 }}
{{- end }}
{{- if $config_col.addContainers }}
{{ toYaml $config_col.addContainers | indent 6 }}
{{- end }}
      volumes:
{{- if $config_col.pvc }}{{- else }}
        - name: datastore
          emptyDir: {}
{{- end }}
{{- if .Values.WAL.archive.enable }}
{{- if $config_col.pvc }}{{- else }}
        - name: wal-archive
          emptyDir: {}
{{- end }}
{{- end }}
        - name: {{$app_name}}-scripts
          configMap:
            name: {{$app_name}}-scripts
            defaultMode: 0777
        - name: {{$app_name}}-cfg
          configMap:
            name: {{$app_name}}-cfg
            defaultMode: 0777
{{- if $config_col.volumes }}
{{ toYaml $config_col.volumes | indent 8 }}
{{- end }}
      
