{{ $app_name := include "global.app_name" . -}}
{{ $chart_name := include "global.chart_full_name" . -}}
{{ $config_col := .Values.gtm -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $app_name }}-svc-gtm
  labels:
    app: {{ $app_name }}
    chart: {{ $chart_name }}
    type: gtm
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.managers_port }}
    protocol: TCP
    targetPort: {{ .Values.managers_port }}
    name: gtm
  selector:
    app: {{ $app_name }}
    chart: {{ $chart_name }}
    type: gtm
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: {{ $app_name }}-gm
  labels:
    app: {{ $app_name }}
    chart: {{ $chart_name }}
    type: gtm
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
spec:
  serviceName: {{ $app_name }}-svc-gm
  replicas: 1
  podManagementPolicy: Parallel
  volumeClaimTemplates:
{{- if $config_col.pvc }}
    - metadata:
        name: datastore
      spec:
        accessModes: [ "ReadWriteOnce" ]
{{ toYaml $config_col.pvc | indent 8 }}
{{- end }}
{{- if $config_col.addVolumeClaims }}
{{ toYaml $config_col.addVolumeClaims | indent 4 }}
{{- end }}
  selector:
    matchLabels:
      app: {{ $app_name }}
      chart: {{ $chart_name }}
      type: gtm
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 6 }}
{{- end }}
{{- if $config_col.injectDepYaml }}
{{ toYaml $config_col.injectDepYaml | indent 2 }}
{{- end }}
  template:
    metadata:
      labels:
        app: {{ $app_name }}
        chart: {{ $chart_name }}
        type: gtm
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 8 }}
{{- end }}
    spec:
      securityContext:
        fsGroup: 3000
{{- if $config_col.injectSpecYaml }}
{{ toYaml $config_col.injectSpecYaml | indent 6 }}
{{- end }}
      containers:
      - name: gtm
        image: {{ .Values.image }}
        command:
          - bash
          - /entry/gtm_entrypoint
        envFrom:
        - configMapRef:
            name: {{$app_name}}-envs
        ports:
          - containerPort: {{ .Values.managers_port }}
            name: gtm
        resources:
{{- if $config_col.resources }}
{{ toYaml $config_col.resources | indent 10 }}
{{- end }}
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NODE_TYPE
            value: proxy
        volumeMounts:
          - name: {{$app_name}}-scripts
            mountPath: /entry
          - name: {{$app_name}}-cfg
            mountPath: /config
          - name: datastore
            mountPath: {{ .Values.homedir }}/storage
{{- if $config_col.volumeMounts }}
{{ toYaml $config_col.volumeMounts | indent 10 }}
{{- end }}
{{- if $config_col.injectMainContainerYaml }}
{{ toYaml $config_col.injectMainContainerYaml | indent 8 }}
{{- end }}
{{- if $config_col.addContainers }}
{{ toYaml $config_col.addContainers | indent 6 }}
{{- end }}  
      volumes:
{{- if $config_col.pvc }}{{- else }}
        - name: datastore
          emptyDir: {}
{{- end }}
        - name: {{$app_name}}-scripts
          configMap:
            name: {{$app_name}}-scripts
            defaultMode: 0777
        - name: {{$app_name}}-cfg
          configMap:
            name: {{$app_name}}-cfg
            defaultMode: 0777
{{- if $config_col.volumes }}
{{ toYaml $config_col.volumes | indent 8 }}
{{- end }}