# generate a transiant postgres-xl db. This db will 
# NOT be able to withstand restarts.
releases:
  - name: {{CHART_NAME}}
    # Use of a specific relaease.
    # chart: https://github.com/LamaAni/postgres-xl-helm/archive/0.5.0.tar.gz
    # Chart in directory
    chart: ../../../
    values:
      - ./values.yaml
      # can also added inline, example:
      # - datanodes:
      #     count: 4  
      #   coordinators:
      #     count: 2
      - envs:
          CONNECTION_POOL_CREATE_PGSHADOW_LOOKUP: |-
{{ readFile "../sql/connection-pool-create-pgshadow-lookup.sql" | indent 12 }}