apiVersion: v1
kind: Secret
metadata:
  name:  pgxl-passwords-collection
type: Opaque
data:
  # You must byte64 encode your values. See: https://kubernetes.io/docs/concepts/configuration/secret/
  pgpass: "bGFtYQ=="