apiVersion: v1
kind: Secret
metadata:
  name:  pgxl-passwords-collection
type: Opaque
data:
  # You must byte64 encode your values. See: https://kubernetes.io/docs/concepts/configuration/secret/
  # the password is: "this_is_not_a_password"
  pgpass: dGhpc19pc19ub3RfYV9wYXNzd29yZA==