# used limited resources to allow this
# deployment to be tested on local systems.
# Recommended values can be found in README and 
# in the values file in this chart.

small_resource_limit: &small_resource_limit
  limits:
    memory: "500Mi"
    cpu: "250m"

datanodes:
  count: 1
  resources: *small_resource_limit
coordinators:
  count: 1
  resources: *small_resource_limit
proxies:
  count: 1
  resources: *small_resource_limit
  enabled: true

security:
  passwords_secret_name: pgxl-passwords-collection
  pg_password: pgpass