datanodes:
  count: 1
  resources:
    limits:
      memory: "500Mi"
      cpu: "250m"
coordinators:
  count: 1
  resources:
    limits:
      memory: "500Mi"
      cpu: "500m"
proxies:
  count: 1
  resources:
    limits:
      memory: "500Mi"
      cpu: "250m"
  enabled: true

security:
  passwords_secret_name: pgxl-passwords-collection
  pg_password: pgpass