gtm:
  pvc:
    resources:
        requests:
          storage: 100Mi
datanodes:
  count: 4
  pvc:
    resources:
        requests:
          storage: "4Gi"
coordinators:
  count: 2
  pvc:
    resources:
        requests:
          storage: 100Mi
proxies:
  count: 1
  enabled: true