image: sstubbs/pgxl:latest

gtm:
  resources: null
datanodes:
  count: 1
  resources: null
coordinators:
  count: 1
  resources: null
proxies:
  count: 1
  enabled: true
  resources: null

security:
  passwords_secret_name: {{SECRET_NAME}}
  pg_password: {{SECRET_KEY}}
  postgres_auth_type: md5

service:
  type: ClusterIP

on_load:
  # set to 1 so if database create fails we will see
  # it right away.
  back_off_limit: 1
  enabled: true
  resources: null
  init:
    - name: connection_pool_create_base_user.sh
      script: |-
        psql -c "$CONNECTION_POOL_CREATE_BASE_USER"
    - name: connection_pool_create_pgshadow_lookup.sh
      script: |-
        psql -c "$CONNECTION_POOL_CREATE_PGSHADOW_LOOKUP"
    - name: connection_pool_create_pgshadow_lookup_template1.sh
      script: |-
        psql -d template1 -c "$CONNECTION_POOL_CREATE_PGSHADOW_LOOKUP"
        psql -c "$CLEAN_CONNECTIONS_TO_TEMPLATE1"